### ISSUE TITLE
CocoaPods上暂时搜不到咱们的框架？？？

### ISSUE THREAD

**Issue by dito010** [weijingyunIOS/JYDatabase#1]
CocoaPods上暂时搜不到咱们的框架？？？

**Comment by weijingyunIOS** [comment]
你是不是最新的cocopods ，我是用的0.39.0版本，是有的

**Comment by weijingyunIOS** [comment]
bogon:~ weijingyun$ pod search JYDatabase

-> JYDataBase (1.0.3)
   对FMDB的轻量级封装，帮助快速创建管理移动端数据库.
   pod 'JYDataBase', '~> 1.0.3'
- Homepage: https://github.com/weijingyunIOS/JYDatabase
- Source:   https://github.com/weijingyunIOS/JYDatabase.git
- Versions: 1.0.3, 1.0.2, 1.0.1, 1.0.0 [master repo]

bogon:~ weijingyun$ pod --version
0.39.0

**Comment by dito010** [comment]
终于搞定了,今天安装了一天,还是搜索不到,但是已经集成到项目了,谢谢!
