### ISSUE TITLE
swift

### ISSUE THREAD

**Issue by sumlunmao** [weijingyunIOS/JYDatabase#2]
could u please pull a version of swift? 我这导入你的框架，但conditions这个block不好用呀，比如我需要用到“limit”关键字，我不知该如何转换，谢谢

**Comment by weijingyunIOS** [comment]
很抱歉现在才看到，关于JYQueryConditions 只是针对属性查询判断的简化，想“limit” 等复杂查询的我并没提供，可以直接用 - (JYQueryConditions * (^)(NSString *str))sqlStr; 自己写sql语句就好了。 关于出 swift 有所考虑，但多半不会用 FMDB封装。realm数据库是相当不错的，可以研究一下。
