### ISSUE TITLE
类型判断出错引起crash（Bug，已fix）

### ISSUE THREAD

**Issue by NeilChan** [weijingyunIOS/JYDatabase#3]
hello，我在使用的时候。在某些情况（比较难复现）：
-> JYContentTable.m 
-> - (NSArray *)conversionAttributeType:(NSString *)aType 
-> NSString *str = kTypeArray[index];
出现了数组越界抛出的crash，根据友盟的错误分析跟Xcode获得的错误记录来看是：
*** -[__NSArrayI objectAtIndex:]: index 2147483647 beyond bounds [0 .. 14]

我检查了我所用的模型数据中出现的只有 ：BOOL、NSString、NSNumber几种类型数据，更细致的过程是我在查找该表（假设为CNTable）所有缓存的时候进入了这个线程。因为我没办法获得当时crash的一个具体数据，也没有在测试机上重现到这个过程。

不知道你有没有什么其他理解或者排查建议？

**Comment by NeilChan** [comment]
查看类文件进行编译测试，发现上述问题主要是没有对数据格式做32位系统与64位系统区分引起的bug。
例如如下类型会在32位与64位间出现差别：
// NSUInteger : 64 - TQ; 32 - TI
// float: 64 - Td(与double无区别); 32 - Tf
// BOOL: 64 - TB; 32 - Tc
// Boolean_t: 64 - TI; 32 - Ti

解决方案：
1、增加对应映射，在原映射里添加没有的格式。
#define kAttributeArray_32 @[@"Tc",@"TC",@"Td",@"Tf",@"Ti",@"TI",@"Tq",@"TQ",@"T@\"NSMutableString\"",@"T@\"NSString\"",@"T@\"NSData\"",@"T@\"UIImage\"",@"T@\"NSNumber\"",@"T@\"NSDictionary\"",@"T@\"NSMutableDictionary\"",@"T@\"NSMutableArray\"",@"T@\"NSArray\""]
#define kTypeArray_32      @[@"BOOL",@"BOOL",@"DOUBLE",@"FLOAT",@"INTEGER",@"INTEGER",@"INTEGER",@"INTEGER",@"VARCHAR",@"VARCHAR",@"BLOB",@"BLOB",@"BLOB",@"BLOB",@"BLOB",@"BLOB",@"BLOB"]
#define kLenghtArray_32 @[@"1",@"1",@"20",@"10",@"10",@"20",@"10",@"10",@"128",@"128",@"256",@"256",@"64",@"512",@"512",@"512",@"512"]
2、在ContentTable -> - (NSArray *)conversionAttributeType:(NSString *)type；函数进行32位与64位判断区分。

**Comment by weijingyunIOS** [comment]
的确是存在该问题，你使用的版本较低，我之前发现过该问题，已经做了处理，将映射抽了 到了 JYDataBaseConfig ，并且提供了 corresponding属性 供添加额外映射。
