### ISSUE TITLE
外键值连接仅支持String类型，需要在readme中特别声明

### ISSUE THREAD

**Issue by NeilChan** [weijingyunIOS/JYDatabase#4]
我在应用中使用到此新版增加的外健连接多表的功能，感觉readme中的说明并不够完善，另外，外键值仅支持string类型的字段。使用NSNumber一类作为类型，无法获取到相应链接数据。readme中并无说明，为避免其他人踩坑望添加。

**Comment by weijingyunIOS** [comment]
- (NSString *)contentId;                    // 表的主键  
键值 的数据类型 是要做 转化的，我是不太希望用户 使用 其它类型 作为主键和外键的，我会在问当中注明

**Comment by weijingyunIOS** [comment]
但是 主键 是可以用 基本 数据类型的，NSNumber  实际上 是以  BLOB 存入 数据库的，以其查询 写出的 sql 根本 查不出来这是 一个坑。  一般要用于查询的字段 请使用 NSString 和基本数据类型， 不要使用其它对象。
