### ISSUE TITLE
怎么更新表?

### ISSUE THREAD

**Issue by LUJYM** [weijingyunIOS/JYDatabase#8]
你好 你这个updateDB 比如demo里面的JYClassInfo里面的属性className改成了className1 那我要怎么更新这个表?具体步骤是???

**Comment by weijingyunIOS** [comment]
1.如果你使用框架自带封装 的升级，只要
// 返回当前数据库版本，只要数据表有修改 返回版本号请 ＋1 默认返回 1
- (NSInteger)getCurrentDBVersion{
    return 4;
} 即可。自带升级的实现 在 2.1 数据库升级的实现 - (void)updateDB:(FMDatabase *)aDB 有详细说明。
这样升级会导致   className 列的数据丢失。
2.你可以 自己写 sql语句实现升级。
