### ISSUE TITLE
tableViceKey 我不想设置可以么

### ISSUE THREAD

**Issue by suddenly1990** [weijingyunIOS/JYDatabase#9]
您好：
    我有两个类  分别为一级 二级
    其中一级类下有一个数组想和二级类关联 也就是说数组填充的是二级类 除此之外没有任何关系
    我用到了您的这个方法：
  - (NSDictionary<NSString *, NSDictionary *> *)associativeTableField{

    JMDownLoadMidTable *table = [JMDBService shared].goodsDB.downLoadMidTable;
    return @{
             @"shopList" : @{
                     tableContentObject : table,
                      tableViceKey       : @""
                     }
             };
 }
 其中   tableViceKey  不知道应该去添加什么 （试了下不写或者是空字符串 报错）

**Comment by weijingyunIOS** [comment]
tableViceKey是对应的外建，需要通过这个字段 去二级类查询。 如果你对二级类没有太高的查询要求，实际可以将 数组 通过 YYModel 转为 JSON 存储
